// <auto-generated />
using System;
using CromosList.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CromosList.Migrations
{
    [DbContext(typeof(CromosListDbContext))]
    [Migration("20260831191454_JugadorEquiposNtoM")]
    partial class JugadorEquiposNtoM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CromosList.Models.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EditorialId")
                        .HasColumnType("bigint")
                        .HasColumnName("editorial_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Temporada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("temporada");

                    b.HasKey("Id");

                    b.HasIndex("EditorialId");

                    b.ToTable("album", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.AlbumEquipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlbumId")
                        .HasColumnType("bigint")
                        .HasColumnName("album_id");

                    b.Property<long>("EquipoId")
                        .HasColumnType("bigint")
                        .HasColumnName("equipo_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("EquipoId");

                    b.ToTable("album_equipo", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.AlbumTipoCromo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlbumId")
                        .HasColumnType("bigint")
                        .HasColumnName("album_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<long>("TipoCromoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_cromo_id");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("TipoCromoId");

                    b.ToTable("album_tipo_cromo", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.Coleccion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("coleccion", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.Cromo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlbumId")
                        .HasColumnType("bigint")
                        .HasColumnName("album_id");

                    b.Property<long?>("ColeccionId")
                        .HasColumnType("bigint")
                        .HasColumnName("coleccion_id");

                    b.Property<long>("EdicionId")
                        .HasColumnType("bigint")
                        .HasColumnName("edicion_id");

                    b.Property<long>("EquipoId")
                        .HasColumnType("bigint")
                        .HasColumnName("equipo_id");

                    b.Property<long>("JugadorId")
                        .HasColumnType("bigint")
                        .HasColumnName("jugador_id");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<long?>("PublicacionId")
                        .HasColumnType("bigint")
                        .HasColumnName("publicacion_id");

                    b.Property<long>("TipoCromoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tipo_cromo_id");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ColeccionId");

                    b.HasIndex("EdicionId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PublicacionId");

                    b.HasIndex("TipoCromoId");

                    b.ToTable("cromo", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.Edicion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("edicion", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.Editorial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("editorial", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.Equipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("equipo", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.Jugador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.HasKey("Id");

                    b.ToTable("jugador", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.Publicacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EdicionId")
                        .HasColumnType("bigint")
                        .HasColumnName("edicion_id");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Temporada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("temporada");

                    b.HasKey("Id");

                    b.HasIndex("EdicionId");

                    b.ToTable("publicacion", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.TipoCromo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipo_cromo", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.UsuarioCromo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CromoId")
                        .HasColumnType("bigint")
                        .HasColumnName("cromo_id");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CromoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuario_cromo", (string)null);
                });

            modelBuilder.Entity("equipo_jugador", b =>
                {
                    b.Property<long>("equipo_id")
                        .HasColumnType("bigint");

                    b.Property<long>("jugador_id")
                        .HasColumnType("bigint");

                    b.HasKey("equipo_id", "jugador_id");

                    b.HasIndex("jugador_id");

                    b.ToTable("equipo_jugador", (string)null);
                });

            modelBuilder.Entity("CromosList.Models.Album", b =>
                {
                    b.HasOne("CromosList.Models.Editorial", "Editorial")
                        .WithMany("Albums")
                        .HasForeignKey("EditorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editorial");
                });

            modelBuilder.Entity("CromosList.Models.AlbumEquipo", b =>
                {
                    b.HasOne("CromosList.Models.Album", "Album")
                        .WithMany("AlbumEquipos")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CromosList.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("CromosList.Models.AlbumTipoCromo", b =>
                {
                    b.HasOne("CromosList.Models.Album", "Album")
                        .WithMany("AlbumTiposCromo")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CromosList.Models.TipoCromo", "TipoCromo")
                        .WithMany()
                        .HasForeignKey("TipoCromoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("TipoCromo");
                });

            modelBuilder.Entity("CromosList.Models.Cromo", b =>
                {
                    b.HasOne("CromosList.Models.Album", "Album")
                        .WithMany("Cromos")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CromosList.Models.Coleccion", "Coleccion")
                        .WithMany("Cromos")
                        .HasForeignKey("ColeccionId");

                    b.HasOne("CromosList.Models.Edicion", "Edicion")
                        .WithMany("Cromos")
                        .HasForeignKey("EdicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CromosList.Models.Equipo", "Equipo")
                        .WithMany("Cromos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CromosList.Models.Jugador", "Jugador")
                        .WithMany("Cromos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CromosList.Models.Publicacion", "Publicacion")
                        .WithMany("Cromos")
                        .HasForeignKey("PublicacionId");

                    b.HasOne("CromosList.Models.TipoCromo", "TipoCromo")
                        .WithMany("Cromos")
                        .HasForeignKey("TipoCromoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Coleccion");

                    b.Navigation("Edicion");

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");

                    b.Navigation("Publicacion");

                    b.Navigation("TipoCromo");
                });

            modelBuilder.Entity("CromosList.Models.Publicacion", b =>
                {
                    b.HasOne("CromosList.Models.Edicion", "Edicion")
                        .WithMany("Publicaciones")
                        .HasForeignKey("EdicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edicion");
                });

            modelBuilder.Entity("CromosList.Models.UsuarioCromo", b =>
                {
                    b.HasOne("CromosList.Models.Cromo", "Cromo")
                        .WithMany("UsuariosCromo")
                        .HasForeignKey("CromoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CromosList.Models.Usuario", "Usuario")
                        .WithMany("Cromos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cromo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("equipo_jugador", b =>
                {
                    b.HasOne("CromosList.Models.Equipo", null)
                        .WithMany()
                        .HasForeignKey("equipo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CromosList.Models.Jugador", null)
                        .WithMany()
                        .HasForeignKey("jugador_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CromosList.Models.Album", b =>
                {
                    b.Navigation("AlbumEquipos");

                    b.Navigation("AlbumTiposCromo");

                    b.Navigation("Cromos");
                });

            modelBuilder.Entity("CromosList.Models.Coleccion", b =>
                {
                    b.Navigation("Cromos");
                });

            modelBuilder.Entity("CromosList.Models.Cromo", b =>
                {
                    b.Navigation("UsuariosCromo");
                });

            modelBuilder.Entity("CromosList.Models.Edicion", b =>
                {
                    b.Navigation("Cromos");

                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("CromosList.Models.Editorial", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("CromosList.Models.Equipo", b =>
                {
                    b.Navigation("Cromos");
                });

            modelBuilder.Entity("CromosList.Models.Jugador", b =>
                {
                    b.Navigation("Cromos");
                });

            modelBuilder.Entity("CromosList.Models.Publicacion", b =>
                {
                    b.Navigation("Cromos");
                });

            modelBuilder.Entity("CromosList.Models.TipoCromo", b =>
                {
                    b.Navigation("Cromos");
                });

            modelBuilder.Entity("CromosList.Models.Usuario", b =>
                {
                    b.Navigation("Cromos");
                });
#pragma warning restore 612, 618
        }
    }
}
